# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_adress', models.CharField(max_length=200)),
                ('company_contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('hours_worked', models.CharField(max_length=200)),
                ('date_worked', models.CharField(max_length=200)),
                ('hourly_pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('workers_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
