# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('pay', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='workers_phone',
            new_name='workers_contacts',
        ),
        migrations.AddField(
            model_name='pay',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.Worker'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.Pay'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.Worker'),
        ),
    ]
