# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_auto_20170807_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_id',
            new_name='passport_number',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='company',
        ),
    ]
