# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_auto_20170808_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='passport_number',
            field=models.CharField(max_length=200),
        ),
    ]
